development:
  adapter: postgis
  encoding: unicode
  database: iom_development

test:
  adapter: postgis
  template: template_postgis
  encoding: unicode
  database: ngoaidmap_test

staging:
  adapter: postgresql
  template: template_postgis
  encoding: unicode
  database: iom_production_v2
  username: postgres
  password:

smbtc:
  adapter: postgresql
  template: template_postgis
  encoding: unicode
  database: iom_production_v2
  username: postgres
  password:

production:
  adapter: postgresql
  template: template_postgis
  encoding: unicode
  host: localhost
  database: iom_production_v2
  username: postgres
  password:
