development:
  adapter: postgresql
  template: template_postgis
  encoding: unicode
  database: iom_development
  username: postgres
  password:

test:
  adapter: postgresql
  template: template_postgis
  encoding: unicode
  database: iom_test
  username: postgres
  password:

